# Generated by Django 3.1.6 on 2021-04-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.BooleanField(default=False),
        ),
    ]
